### ISSUE TITLE
Publish to Coinmarketcap

### ISSUE THREAD

**Issue by rudolfschmidt** [cranklin/crankycoin#2]
Hi, found your code searching for example to create my own coin. Interesting code, did you try to publish your coin at index pages like coinmarketcap.com, its still not listed, why?

**Comment by cranklin** [comment]
Hi @rudolfschmidt 
Thanks for your interest!
This coin needs just a little more work before it can go live.  Originally, I intended for cranky coin to be just an educational demo.  I've since added to it and would love to see it go live with the community's help and support (without an ICO).  :)

**Comment by rudolfschmidt** [comment]
I would like to support you and develop on it, but Python is not my world, are you interested to do something in Java?

**Comment by cranklin** [comment]
Java is also a great choice.  :)

**Comment by rudolfschmidt** [comment]
I would like to create a basic coin with simple functionalities that is able to be listed in coinmarketcap and be traded. I guess its a really interesting time for such things. From that basic you can improve the coin to new mechanism but its good to be started simple.
I have started to develop it, I will publish it and like to invite everyone to join the development.
