### ISSUE TITLE
Difficulty adjustment

### ISSUE THREAD

**Issue by keyvank** [cranklin/crankycoin#4]
Hi!
Thank you for this great project!
I had a confusion with the `calculate_hash_difficulty()` function in `blockchain.py`. Shouldn't we divide the calculated `timestamp_data` by `DIFFICULTY_ADJUSTMENT_SPAN`, as we want to adjust the difficulty for just one block?

**Comment by cranklin** [comment]
Thank you @keyvank I think that was a WIP commit that snuck in there.  Please take a look and see if this new difficulty adjustment method makes sense.  I included the corresponding unit tests in this commit as well.

**Comment by keyvank** [comment]
Thank you @cranklin It makes sense now. But is there any particular reason why we don't just compare every block with its previous block? I mean, why do we set `DIFFICULTY_ADJUSTMENT_SPAN` to values higher than 1?

**Comment by cranklin** [comment]
Yes.  Block timestamps are not reliably 10 minutes apart.  That's why we go back in time and take n number of blocks and calculate the average time between those blocks.
