### ISSUE TITLE
command publickey does not work for me

### ISSUE THREAD

**Issue by japelt** [cranklin/crankycoin#8]
Hi,

I tried to run the command publickey but I got the below error. Any idea hoe to fix this?
Cranky Coin (CRNK) wallet > publickey
Traceback (most recent call last):
  File "run.py", line 218, in <module>
    main(sys.argv[1:])
  File "run.py", line 210, in main
    client()
  File "run.py", line 75, in client
    print(wallet.get_public_key())
  File "/home/jani/crankycoin-master/crankycoin/wallet.py", line 27, in get_public_key
    return self.__public_key__.to_hex()
AttributeError: 'PublicKey' object has no attribute 'to_hex'

This is the first time I'm running this and there is no publickey but I think it should be created now.

**Comment by japelt** [comment]
I re-installed and publickey command started to work.
Thanks.

**Comment by Aareon** [comment]
@japelt if this is resolved, mind closing?
